<a href="https://colab.research.google.com/github/dejanbatanjac/pytorch-learning-101/blob/master/PyTorch_nn_Module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import torch.nn as nn

class Module0(nn.Module):
    def __init__(self):
        super().__init__()
        
    # we don't return a thing 
    def forward(self)->None: 
        print("Module0:forward")
        
# we create a module instance m0
m0 = Module0().cuda()

# we explicitely run the forward method
m0.forward()
        
m0 = Module0().cuda() 
m0()


    


Module0:forward
Module0:forward


In [3]:
# these are not identical even tough it looks like
m0()
m0.forward()

# we should always call m0()


Module0:forward
Module0:forward


In [4]:
#Problems

# P1. we have no params so we cannot learn
# P2. our forward doesn't take any input and doesn't returns any output

t = [o.numel() for o in m0.parameters() ]
t, sum(t)

([], 0)

In [0]:
#fixing the problems P1 and P2 in Module1

import torch
import torch.nn as nn

# Creating the single linear layer = one matrix tranformation
class Module1(nn.Module):
    def __init__(self):
        super().__init__()
        self.l1 = nn.Linear(10,100)        
        
    
    def forward(self,x)->None: 
        print("Module1:forward")
        return self.l1(x)
        
# we create a module instance m1
m1 = Module1()



In [14]:
# testing out if we have parameters

t = [p.numel() for p in m1.parameters() if p.requires_grad ]
print(t, sum(t))

#([1000, 100], 1100)
# 1000 parameters in W 
# 100 parameters in b and 
# 1100 parametes in total

# trying some input 10 batches on 10 features

inp = torch.empty(10, 10).uniform_()
print(inp)
out = m1(inp)
print(out)
#output has 10 batches of 100 features

[1000, 100] 1100
tensor([[0.1943, 0.8545, 0.8793, 0.7102, 0.4046, 0.2718, 0.7608, 0.9223, 0.3837,
         0.3083],
        [0.8162, 0.0176, 0.7427, 0.2288, 0.7135, 0.8049, 0.1336, 0.0455, 0.2951,
         0.0237],
        [0.1867, 0.6787, 0.9078, 0.3336, 0.3317, 0.3092, 0.1874, 0.0796, 0.3572,
         0.7660],
        [0.2215, 0.0964, 0.3425, 0.7453, 0.1788, 0.1240, 0.9839, 0.6630, 0.8446,
         0.4913],
        [0.7615, 0.5373, 0.0317, 0.9994, 0.5345, 0.5920, 0.5245, 0.6511, 0.7182,
         0.2406],
        [0.8722, 0.4567, 0.7412, 0.3816, 0.2416, 0.4976, 0.5791, 0.0472, 0.6985,
         0.1834],
        [0.3595, 0.9011, 0.8088, 0.3622, 0.1385, 0.0411, 0.9082, 0.4432, 0.7449,
         0.5659],
        [0.1207, 0.3547, 0.7430, 0.7472, 0.1694, 0.7854, 0.9672, 0.9447, 0.4042,
         0.1316],
        [0.5010, 0.8589, 0.1002, 0.3644, 0.4383, 0.9904, 0.5604, 0.5179, 0.9103,
         0.0907],
        [0.2012, 0.6918, 0.6730, 0.4609, 0.2229, 0.7725, 0.7720, 0.6014, 0.6474,
         0.

In [0]:
import torch
import torch.nn as nn

# adding few more different layers
class Module2(nn.Module):
    def __init__(self):
        super().__init__()
        self.l1 = nn.Linear(50*50,100)
        self.l2 = nn.ReLU()
        self.l3 = nn.Linear(100,100)
        self.l4 = nn.Tanh()        
        self.l5 = nn.Linear(100,10) 
        self.l6 = nn.LogSoftmax(dim=0)
        
    # we don't return a thing (read:None), and don't take a thing
    def forward(self,x): 
        print("Module2:forward")
        x = self.l1(x)
        x = self.l2(x)
        x = self.l3(x)
        x = self.l4(x)
        x = self.l5(x)        
        out = self.l6(x)
        return out
        
        
# we create a module instance m2
m2 = Module2()




In [52]:
# the total number of parameters grow up to 261k
# we must be carefull with params, as they take out all memory
t = [p.numel() for p in m2.parameters() ]
t, sum(t)

#([250000, 100, 10000, 100, 1000, 10], 261210)
# total number of parameter is ~ 261K

([250000, 100, 10000, 100, 1000, 10], 261210)

In [71]:
# like before we create the input tensor
inp = torch.empty(10, 50*50).uniform_(-1, 1)
print(inp)
out = m2(inp)
print(out.shape)
print(out)

tensor([[-0.4002,  0.0428, -0.3155,  ..., -0.4366,  0.5195, -0.6968],
        [-0.0099,  0.3947, -0.9717,  ...,  0.6382, -0.5189,  0.9321],
        [-0.9478, -0.6170, -0.0410,  ..., -0.1291, -0.8287,  0.4782],
        ...,
        [-0.8164,  0.3744, -0.1388,  ...,  0.7256, -0.8553, -0.8022],
        [ 0.4623,  0.0334,  0.0570,  ...,  0.2202,  0.0360, -0.4752],
        [ 0.9311, -0.7473, -0.1324,  ...,  0.8351,  0.3134,  0.4498]])
Module2:forward
torch.Size([10, 10])
tensor([[-2.2888, -2.2168, -2.3781, -2.2525, -2.3557, -2.3032, -2.3818, -2.2191,
         -2.2785, -2.3744],
        [-2.2999, -2.3793, -2.1945, -2.2368, -2.3011, -2.2784, -2.2420, -2.1849,
         -2.2610, -2.3314],
        [-2.3537, -2.2859, -2.3454, -2.2686, -2.2640, -2.3539, -2.3098, -2.3816,
         -2.2885, -2.2711],
        [-2.3157, -2.3711, -2.2845, -2.3315, -2.3559, -2.2588, -2.3438, -2.2919,
         -2.2535, -2.3107],
        [-2.3277, -2.2396, -2.3399, -2.3055, -2.4148, -2.2994, -2.3074, -2.3485,
         -2.