<a href="https://colab.research.google.com/github/dejanbatanjac/pytorch-learning-101/blob/master/PyTorch_General.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
# check if you have GPU
import torch
torch.cuda.is_available()
print(torch.__version__)

1.0.1.post2


In [0]:
import torch

t = torch.tensor(1, dtype=torch.float32, requires_grad=True)
print(t, t.shape)

t = torch.tensor([1], dtype=torch.float32, requires_grad=True)
print(t, t.shape)

t = torch.tensor([[1]], dtype=torch.float32, requires_grad=True)
print(t, t.shape)

tensor(1., requires_grad=True) torch.Size([])
tensor([1.], requires_grad=True) torch.Size([1])
tensor([[1.]], requires_grad=True) torch.Size([1, 1])


In [0]:
# unsqueeze
import torch
x = torch.tensor([1, 2, 3, 4])
print(x,x.shape)
print(torch.unsqueeze(x, 0),torch.unsqueeze(x, 0).shape)
print(torch.unsqueeze(x, 1),torch.unsqueeze(x, 1).shape)

print("...")
print(x.view(-1,1), x.view(-1,1).shape)
print(x.view(1,-1), x.view(1,-1).shape)


tensor([1, 2, 3, 4]) torch.Size([4])
tensor([[1, 2, 3, 4]]) torch.Size([1, 4])
tensor([[1],
        [2],
        [3],
        [4]]) torch.Size([4, 1])
...
tensor([[1],
        [2],
        [3],
        [4]]) torch.Size([4, 1])
tensor([[1, 2, 3, 4]]) torch.Size([1, 4])


In [8]:
import torch
x = torch.tensor([1, 2, 3, 4]).to("cuda")
print(x.tolist()) #returns the list
print(x.tolist()[0]) #returns the first element from the list
print(x.data) #returns the tensor
print(x.data[0]) # returns the first element tensor
print(x.data[0]) # returns the first element tensor
print(x.data[0].item()) # returns the first element

[1, 2, 3, 4]
1
tensor([1, 2, 3, 4], device='cuda:0')
tensor(1, device='cuda:0')
tensor(1, device='cuda:0')
1


In [0]:
from torch.utils.data import DataLoader, Dataset
import numpy as np

x1 = np.array([13,3,28,24,33,2,3,62,47,58])
x2 = np.array([15,21,30,27,17,3,3,54,54,44])
x3 = np.array([32,2,27,19,2,3,32,3,60,47])

#stack multiple tensors using np.stack

md = DataLoader( np.stack([x1,x2,x3], axis=1), batch_size=512)
#??np.stack


In [0]:
import torch
a = [i for i in range(50)]
b = [i for i in range(50)]
c = [i for i in range(50)]

#h
A = torch.Tensor(a)
B = torch.FloatTensor(b)
C = torch.FloatTensor(c)
h=[A,B,C]

print(len(h))
print(h[0].size(), h[0])

3
torch.Size([50]) tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
        14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26., 27.,
        28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39., 40., 41.,
        42., 43., 44., 45., 46., 47., 48., 49.])


In [0]:
import torch 
import torch.utils.data as utils
import numpy as np


# from np.array to tensor
np_x = [np.array([[1,2],[1,3]]),np.array([[5,6],[7,8]])] # a list of numpy arrays
np_y = [np.array([2]), np.array([3])] # another list of numpy arrays (targets)

tx = torch.stack([torch.Tensor(i) for i in np_x]) # transform to torch tensors
ty = torch.stack([torch.Tensor(i) for i in np_y])

print("tensor x:", tx)
print("tensor y:", ty)
print("tensor x shape:", tx.shape)
print("tensor y shape:", ty.shape)

# Dataset is an abstract class. We cannot use it directly.
# We use TensorDataset class.
# The tensor(s) in there should have the same size of the first dimension.

# create datset
ds = utils.TensorDataset(tx, ty) 

# try setting shuffle=False|True
dl = utils.DataLoader(ds, batch_size=1, shuffle=False) 


# DataLoader knows the batch size. Try setting {1|2} instead
dl = utils.DataLoader(ds, batch_size=2, shuffle=True) 


it =iter(dl)
works = True
while works:
    try:
        *r, l = next(it)
        print("--")
        print(r)
        print(l)
        

    except Exception as e:
        print(e)
        works = False


tensor x: tensor([[[1., 2.],
         [1., 3.]],

        [[5., 6.],
         [7., 8.]]])
tensor y: tensor([[2.],
        [3.]])
tensor x shape: torch.Size([2, 2, 2])
tensor y shape: torch.Size([2, 1])
--
[tensor([[[5., 6.],
         [7., 8.]],

        [[1., 2.],
         [1., 3.]]])]
tensor([[3.],
        [2.]])



In [0]:
import torch 
import torch.utils.data as utils

# from list to tensor
l_x = [ [[1,2],[1,3]], [[5,6],[7,8]] ] # a list of numpy arrays
l_y = [ [2],[2]] # another list of numpy arrays (targets)

# transform to torch tensors
tx = torch.stack([torch.Tensor(i) for i in l_x]) 
ty = torch.stack([torch.Tensor(i) for i in l_y])

print(tx)
print(ty)
print(tx.shape, ty.shape)

# Dataset is an abstract class. We cannot use it directly.
# We use TensorDataset class.
# The tensor(s) in there should have the same size of the first dimension.

# create datset
ds = utils.TensorDataset(tx, ty) 
# create dataloader
dl = utils.DataLoader(ds, batch_size=1, shuffle=True) 

# print what we have inside
print("==")
for i in ds: print(i)
print(type(i))
print("==")
for i in dl: print(i)
print(type(i))
    

tensor([[[1., 2.],
         [1., 3.]],

        [[5., 6.],
         [7., 8.]]])
tensor([[2.],
        [2.]])
torch.Size([2, 2, 2]) torch.Size([2, 1])
==
(tensor([[1., 2.],
        [1., 3.]]), tensor([2.]))
(tensor([[5., 6.],
        [7., 8.]]), tensor([2.]))
<class 'tuple'>
==
[tensor([[[5., 6.],
         [7., 8.]]]), tensor([[2.]])]
[tensor([[[1., 2.],
         [1., 3.]]]), tensor([[2.]])]
<class 'list'>


In [0]:
import torch
import torch.nn as nn

tensor = torch.randn((1, 2), requires_grad=True)

print(torch.tanh(tensor))
print(nn.Tanh()(tensor))

#nn.functional.tanh is deprecated
#print(torch.nn.functional.tanh(tensor))

tensor([[0.8146, 0.7732]], grad_fn=<TanhBackward>)
tensor([[0.8146, 0.7732]], grad_fn=<TanhBackward>)


In [0]:
import torch


x = torch.zeros(2,1,2,1,2)
print(x.size())

# all dimensions of size 1 will be removed
y = torch.squeeze(x)
print(y.size())

# we may specify particular dimension to squeeze
# in here 0 will not do anything
y = torch.squeeze(x, 0)
print(y.size())

# we may specify particular dimension to squeeze
# in here 1 will squeeze single dimension
y = torch.squeeze(x, 1)
print(y.size())

torch.Size([2, 1, 2, 1, 2])
torch.Size([2, 2, 2])
torch.Size([2, 1, 2, 1, 2])
torch.Size([2, 2, 1, 2])


In [0]:
# * 
*bb, bbb = [1,2,3,4,5,6,7]
print(bb)
print(bbb)

[1, 2, 3, 4, 5, 6]
7


In [0]:
import torch


x = torch.zeros(2,1)
print(x.size())
print(x)

# all dimensions of size 1 will be removed
y = torch.squeeze(x)
print(y.size())
print(y)

# to be same as x
z = torch.unsqueeze(y, dim=1)
print(z.size())
print(z)



torch.Size([2, 1])
tensor([[0.],
        [0.]])
torch.Size([2])
tensor([0., 0.])
torch.Size([2, 1])
tensor([[0.],
        [0.]])


In [0]:
# from np.array -> tensor
import numpy as np
import torch

#a = np.array([1, 2, 3])
a = np.random.rand(3,2)
t = torch.from_numpy(a)
print(t)



tensor([[0.0307, 0.9624],
        [0.8289, 0.9290],
        [0.4454, 0.1031]], dtype=torch.float64)


In [0]:
print(torch.__version__) #1.0.1.post2
#stacking example
a = torch.randn(2,3,4)
b = torch.randn(2,3)
print(a.size())
print(b.size())
b = torch.unsqueeze(b, dim=2)  # 2, 3, 1
print(b.size())



1.0.1.post2
torch.Size([2, 3, 4])
torch.Size([2, 3])
torch.Size([2, 3, 1])


In [0]:
import torch
print(torch.__version__) # 1.0.1.post2
#stacking example
a = torch.randn(2,3,4)
b = torch.randn(2,3)
print(a.size()) # 2, 3, 4
print(b.size()) # 2, 3
b = torch.unsqueeze(b, dim=2)  
print(b.size()) # 2, 3, 1

r = torch.cat((a,b), dim=2)
# r = torch.stack([a, b], dim=2 )
print(r.shape)
print(r)

1.0.1.post2
torch.Size([2, 3, 4])
torch.Size([2, 3])
torch.Size([2, 3, 1])
torch.Size([2, 3, 5])
tensor([[[ 0.0139,  0.6015, -1.6427,  0.9218, -0.4895],
         [-1.4400,  1.8444,  0.5984,  1.7035, -0.7307],
         [-0.4477, -0.0331, -1.7182, -1.9063,  0.6845]],

        [[ 0.2214,  0.3788, -1.1672,  0.4438, -0.6435],
         [ 0.9548,  1.5609,  1.2947,  0.5860,  0.7537],
         [ 1.5375, -0.5452, -0.9654,  1.0114,  0.2838]]])


In [0]:
#transpose 2D Tensor (dimensions 0 <=> 1)
x = torch.randn(2, 3)
print(x)
y = torch.t(x)
print(y)



tensor([[ 0.7538,  0.3490,  0.4196],
        [ 0.8518,  0.2454, -0.4683]])
tensor([[ 0.7538,  0.8518],
        [ 0.3490,  0.2454],
        [ 0.4196, -0.4683]])


In [0]:
#get tensor based on indices

arr=torch.tensor([[1,2],[4,5],[7,8]])
indices_arr=torch.tensor([0,1,0])

ret=arr[[0,1,2],indices_arr]
print(ret, type(ret))

tensor([1, 5, 7]) <class 'torch.Tensor'>


In [0]:
import torch

a = torch.Tensor([1,2,3,4,5])
print(a.shape)
print(a)

a.unsqueeze_(dim=1)
print(a.shape)
print(a)

# a.unsqueeze_(dim=0)
# print(a.shape)
# print(a)



torch.Size([5])
tensor([1., 2., 3., 4., 5.])
torch.Size([5, 1])
tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.]])


In [0]:
# smart indexing example
import torch

x = torch.arange(0, 10, dtype=torch.float)
print(x)

# getting indexes idx where x>=5
idx = x>=5
print(idx, type(idx))

# log on values where x was >=5
x[idx] = torch.log(x[idx])
print(x)

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])
tensor([0, 0, 0, 0, 0, 1, 1, 1, 1, 1], dtype=torch.uint8) <class 'torch.Tensor'>
tensor([0.0000, 1.0000, 2.0000, 3.0000, 4.0000, 1.6094, 1.7918, 1.9459, 2.0794,
        2.1972])


In [0]:
import torch
# random integers 3x3 taken from 0..100 range
x = torch.randint(0, 256, (3, 3))
print(x)

# we take k=1 largest (topk function) per row
k = 2

# kvals = values of the largest
# kidx = indices of the largest
vals, idxs = x.topk(k=k, dim=1)

print("kvals:", vals, "\nkidx:", idxs)

# set all elements to zero
x.zero_()
print(x)

print("dim of x:", x.size(0))  # dimension=3

# set 1 only these elements where we had largest value based on idxs
x[torch.arange(x.size(0))[:, None], idxs] = 1
print(x)

# set 1 only these elements where we had largest value based on idxs
x[torch.arange(x.size(0)).unsqueeze_(1), idxs]=1
print(x)


# print(torch.arange(x.size(0))[:, None])
# print(torch.arange(3).unsqueeze_(1))
# print(torch.arange(x.size(0)).unsqueeze_(1).shape)


tensor([[ 63, 136, 168],
        [135, 132,  43],
        [183, 254,  21]])
kvals: tensor([[168, 136],
        [135, 132],
        [254, 183]]) 
kidx: tensor([[2, 1],
        [0, 1],
        [1, 0]])
tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
dim of x: 3
tensor([[0, 1, 1],
        [1, 1, 0],
        [1, 1, 0]])
tensor([[0, 1, 1],
        [1, 1, 0],
        [1, 1, 0]])


In [0]:
import torch
# given the matrix of indices (index)
# set 1 after the index on a zero tensor a

# size 3x5
a = torch.zeros(3,5)

# tensor of first index where 1 starts
index = torch.LongTensor([2, 1, 3])

print(index)
print(index.unsqueeze(1))

b = torch.arange(a.size(1)).unsqueeze(0) >= index.unsqueeze(1)
print(b)



tensor([2, 1, 3])
tensor([[2],
        [1],
        [3]])
tensor([[0, 0, 1, 1, 1],
        [0, 1, 1, 1, 1],
        [0, 0, 0, 1, 1]], dtype=torch.uint8)


In [0]:
x = torch.arange(1, 17).float().view(1, 1, 4, 4)
x


kh, kw = 2, 2  # kernel_size
dh, dw = 2, 2  # stride


# get all image windows of size (kh, kw) and stride (dh, dw)
input_windows = x.unfold(2, kh, dh).unfold(3, kw, dw)
output = input_windows.contiguous().view(x.size())

output

tensor([[[[ 1.,  2.,  5.,  6.],
          [ 3.,  4.,  7.,  8.],
          [ 9., 10., 13., 14.],
          [11., 12., 15., 16.]]]])

In [0]:
#model.eval() changes the behavior of some layers, e.g. nn.Dropout won’t drop anymore and nn.BatchNorm will use the running estimates instead of the batch stats.
#To save some memory you should wrap your code in with torch.no_grad(): so that the intermediate activations won’t be stored:

with torch.no_grad():
    output = model(factors)

    

# model.train() and model.eval() change the behavior of some layers. 
# nn.Dropout won't drop anymore and nn.BatchNorm layers will use 
# the running estimates instead of the batch statistics. 
# The torch.set_grad_enabled line of code makes sure to clear the intermediate
# values for evaluation, which are needed to backpropagate during 
# training, thus saving memory. 

# It’s comparable to the with torch.no_grad() statement but takes a bool value.
# All new operations in the torch.set_grad_enabled(False) block won’t require gradients. However, the model parameters will still require gradients.
# The running_loss will be “de-averaged” by multiplying it with inputs.size(0). Therefore you should divide by the whole dataset length, not the number of batches.


In [0]:
import torch
def max_pool2d(input, kernel_size, stride):
    kh, kw = kernel_size
    dh, dw = stride
    # get all image windows of size (kh, kw) and stride (dh, dw)
    input_windows = input.unfold(2, kh, dh).unfold(3, kw, dw)
    # view the windows as (kh * kw)
    input_windows = input_windows.contiguous().view(*input_windows.size()[:-2], -1)
    max_val, max_idx = input_windows.max(4)
    return max_val, max_idx

input = torch.randn(10,10)
# print(input)

r = max_pool2d(input, (2,1), (2,4))
print(r)

RuntimeError: ignored

In [0]:
import torch
import torch.nn as nn

# torch.nn.CrossEntropyLoss(weight=None,size_average=True)
# This criterion combines 
# LogSoftMax and NLLLoss in one single class.
# It is useful when training a classification problem with n classes. 

# If provided, the optional argument weights should be a 1D Tensor
# assigning weight to each of the classes. 
# This is particularly useful when you have an unbalanced training set.

# The input is expected to contain scores for each class.input 
# has to be a 2D Tensor of size batch x n.

criterion = nn.CrossEntropyLoss(ignore_index=-1)

target = torch.tensor([-1, 1])
print("target:", target)

output = torch.randn(2, 10, requires_grad=True)
print("output:", output)

loss = criterion(output, target)

loss.backward()
print("loss:", loss)
print("grad:", output.grad)




target: tensor([-1,  1])
output: tensor([[-0.2054,  0.9242,  0.7776,  1.8979,  0.5154, -0.0546,  0.6909,  0.3672,
         -0.4411, -0.2741],
        [-1.7505,  1.7689,  1.6807, -0.1904, -1.1201, -0.1727,  2.5608,  1.2809,
         -0.5408, -0.1375]], requires_grad=True)
loss: tensor(1.6780, grad_fn=<NllLossBackward>)
grad: tensor([[ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
          0.0000,  0.0000],
        [ 0.0055, -0.8132,  0.1710,  0.0263,  0.0104,  0.0268,  0.4123,  0.1146,
          0.0185,  0.0278]])


In [0]:
a = torch.randn(3, 2)
print(a)

res = a.unsqueeze(1) - a
print(res)

res =  a.unsqueeze(0) - a
print(res)

tensor([[ 0.3614,  0.2802],
        [-1.5333, -2.2783],
        [-0.5929, -1.5980]])
tensor([[[ 0.0000,  0.0000],
         [ 1.8946,  2.5586],
         [ 0.9543,  1.8782]],

        [[-1.8946, -2.5586],
         [ 0.0000,  0.0000],
         [-0.9404, -0.6804]],

        [[-0.9543, -1.8782],
         [ 0.9404,  0.6804],
         [ 0.0000,  0.0000]]])
tensor([[[0., 0.],
         [0., 0.],
         [0., 0.]]])


In [0]:
#batch_action seems to be a torch.FloatTensor. You can cast it to a torch.LongTensor using batch_action.long().
import torch
a = torch.Tensor(10)
a = torch.long()
print(a)

TypeError: ignored

In [0]:
x = torch.randn(16, 1580, 201)
idx = torch.tensor(
    [1580, 959, 896, 881, 881, 881, 881, 881, 881, 881, 881, 881, 881, 335, 254, 219]
)
idx = idx - 1  # 0-based index
y = x[torch.arange(x.size(0)), idx]

In [0]:
a = torch.zeros(5, 5)
a[2:, 2:] = torch.ones(3, 3)
print(a)

a = torch.zeros(5, 5)
a[2:, :-2] = torch.ones(3, 3)
print(a)



tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 1., 1., 1.]])
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 0., 0.]])


In [0]:
x = torch.tensor([1, 2, 4, 7, 0])
x_diff = x[1:] - x[:-1]

print(x[1:])
print(x[:-1])
print(x_diff)

tensor([2, 4, 7, 0])
tensor([1, 2, 4, 7])
tensor([ 1,  2,  3, -7])


In [0]:
import torch
x = torch.tensor(20)
print(x)
print(x.shape)
print(x.size())
print(x.dim())
x.unsqueeze_(0)
print(x)
print(x.shape)
print(x.size())
print(x.dim())


tensor(20)
torch.Size([])
torch.Size([])
0
tensor([20])
torch.Size([1])
torch.Size([1])
1
