<a href="https://colab.research.google.com/github/dejanbatanjac/pytorch-learning-101/blob/master/PyTorch_teorija.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [55]:
# check if you have GPU
import torch
torch.cuda.is_available()


True

In [47]:
# torch tensor
import torch

t = torch.tensor(1, dtype=torch.float32, requires_grad=True)
print(t, t.shape)
print(t.numel())

t = torch.tensor([1], dtype=torch.float32, requires_grad=True)
print(t, t.shape)
print(t.numel())

t = torch.tensor([[1]], dtype=torch.float32, requires_grad=True)
print(t, t.shape)
print(t.numel())



tensor(1., requires_grad=True) torch.Size([])
1
tensor([1.], requires_grad=True) torch.Size([1])
1
tensor([[1.]], requires_grad=True) torch.Size([1, 1])
1


In [48]:
import torch.nn as nn
# softmax allways on single dimension

m = nn.Softmax(dim=0)
input = torch.randn(2, 2)
print(input)

# do the softmax on tensor
output = m(input)
print(output)

# show that sum of tensor elemen on 0 axis is 1
print(output.sum(0))

# total sum is 2
print(output.sum())

tensor([[ 0.7773, -2.6343],
        [-0.8799,  0.7595]])
tensor([[0.8399, 0.0325],
        [0.1601, 0.9675]])
tensor([1., 1.])
tensor(2.)


In [0]:
import torch.nn as nn
# softmax exploration

m = nn.Softmax(dim=1)
input = torch.randn(2, 2)
print(input)

# do the softmax on tensor
output = m(input)
print(output)

# show that sum of tensor element on horisontal(1) axis is 1
print(output.sum(1))

#total sum is 2
print(output.sum())

In [45]:
import torch.nn as nn
# softmax on flatten 2D tensor

m = nn.Softmax(dim=0)

# flatten
input = torch.randn(2, 2).view(-1,1)
print(input.shape)
print(input)

# do the softmax on tensor
output = m(input)
print(output)

# show that sum of tensor element on horisontal(1) axis is 1
print(output.sum(0))

#total sum is 2
print(output.sum())

torch.Size([4, 1])
tensor([[-0.4052],
        [-1.0042],
        [ 1.1181],
        [ 0.5519]])
tensor([[0.1144],
        [0.0629],
        [0.5248],
        [0.2979]])
tensor([1.])
tensor(1.)


In [25]:
import numpy as np
print(input[0][0])
print(input[0][1])
print(input[1][0])
print(input[1][1])
print("...")
print(np.exp(input[0][0]))
print(np.exp(input[0][1]))
print(np.exp(input[1][0]))
print(np.exp(input[1][1]))
print("...")

# should be the same value as output[0][0] from above
print(np.exp(input[0][0]) / (np.exp(input[0][0]) + np.exp(input[1][0])) )

tensor(0.6303)
tensor(0.6726)
tensor(1.1563)
tensor(-0.6650)
...
tensor(1.8781)
tensor(1.9594)
tensor(3.1781)
tensor(0.5143)
...
tensor(0.3714)


In [0]:
# implement softmax in numpy on array
import numpy as np
z = np.arange(5) #[0 1 2 3 4]
print(z)
softmax = lambda z:np.exp(z)/np.sum(np.exp(z)) #[0.01165623 0.03168492 0.08612854 0.23412166 0.63640865]
print(softmax(z))

# more gradual
ze = np.exp(z)
print(ze)
zesum = np.sum(ze)
print(zesum)
smx = ze/zesum
print(smx)


tensor([[-1.0077, -0.6758],
        [ 0.2747, -1.0105]])
tensor([[0.4178, 0.5822],
        [0.7833, 0.2167]])
tensor([1., 1.])
tensor(2.)


In [0]:
import torch
output = torch.randn(10, 3)
print(output)
prob = torch.softmax(output, dim=1)
print(prob)

classes = torch.LongTensor(10, 1).random_(0, 3)
class_prob = torch.gather(prob, 1, classes)
print(class_prob)

tensor([[ 0.3757, -1.4919,  0.2931],
        [-1.1108,  1.2481, -1.9035],
        [ 0.6880, -0.4518, -0.8052],
        [ 0.4007,  0.0176,  1.2215],
        [-0.7799,  0.6499, -0.2792],
        [-0.8603,  1.5121,  0.8580],
        [ 0.5565,  0.4327, -0.3191],
        [-0.1452,  1.2623,  0.7672],
        [ 0.6152,  0.4147,  0.5463],
        [-0.3109,  0.6211, -1.1291]])
tensor([[0.4819, 0.0745, 0.4437],
        [0.0831, 0.8793, 0.0376],
        [0.6474, 0.2071, 0.1455],
        [0.2529, 0.1724, 0.5747],
        [0.1465, 0.6119, 0.2416],
        [0.0578, 0.6199, 0.3223],
        [0.4348, 0.3841, 0.1811],
        [0.1320, 0.5393, 0.3287],
        [0.3634, 0.2974, 0.3392],
        [0.2512, 0.6380, 0.1108]])
tensor([[0.4437],
        [0.0831],
        [0.1455],
        [0.2529],
        [0.1465],
        [0.3223],
        [0.1811],
        [0.3287],
        [0.2974],
        [0.1108]])


In [0]:
import torch
import torch.nn as nn

# torch.nn.CrossEntropyLoss(weight=None,size_average=True)
# This criterion combines 
# LogSoftMax and NLLLoss in one single class.
# It is useful when training a classification problem with n classes. 

# If provided, the optional argument weights should be a 1D Tensor
# assigning weight to each of the classes. 
# This is particularly useful when you have an unbalanced training set.

# The input is expected to contain scores for each class.input 
# has to be a 2D Tensor of size batch x n.

criterion = nn.CrossEntropyLoss(ignore_index=-1)

target = torch.tensor([-1, 1])
print("target:", target)

output = torch.randn(2, 10, requires_grad=True)
print("output:", output)

loss = criterion(output, target)

loss.backward()
print("loss:", loss)
print("grad:", output.grad)




target: tensor([-1,  1])
output: tensor([[-0.2054,  0.9242,  0.7776,  1.8979,  0.5154, -0.0546,  0.6909,  0.3672,
         -0.4411, -0.2741],
        [-1.7505,  1.7689,  1.6807, -0.1904, -1.1201, -0.1727,  2.5608,  1.2809,
         -0.5408, -0.1375]], requires_grad=True)
loss: tensor(1.6780, grad_fn=<NllLossBackward>)
grad: tensor([[ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
          0.0000,  0.0000],
        [ 0.0055, -0.8132,  0.1710,  0.0263,  0.0104,  0.0268,  0.4123,  0.1146,
          0.0185,  0.0278]])


In [54]:
# segments

a = torch.randn(3, 2)
print(a.shape)
print(a)


res = a.unsqueeze(1) - a
print(res.shape)
print(res)


res =  a.unsqueeze(0) - a
print(res.shape)
print(res)


torch.Size([3, 2])
tensor([[-0.0730, -1.8375],
        [-1.5152, -0.0811],
        [-1.1114,  0.9640]])
torch.Size([3, 3, 2])
tensor([[[ 0.0000,  0.0000],
         [ 1.4422, -1.7564],
         [ 1.0384, -2.8015]],

        [[-1.4422,  1.7564],
         [ 0.0000,  0.0000],
         [-0.4038, -1.0451]],

        [[-1.0384,  2.8015],
         [ 0.4038,  1.0451],
         [ 0.0000,  0.0000]]])
torch.Size([1, 3, 2])
tensor([[[0., 0.],
         [0., 0.],
         [0., 0.]]])


In [0]:
# CEL for albino

import torch 
import torch.nn as nn

batch_size = 3
a = torch.LongTensor(batch_size).random_(5)
b = torch.randn(batch_size, 5)

criterion = nn.CrossEntropyLoss()
loss = criterion(b, a)
print(loss)

tensor(1.8487)


In [0]:
# onces into zeros

a = torch.zeros(5, 5)
a[2:, 2:] = torch.ones(3, 3)
print(a)

a = torch.zeros(5, 5)
a[2:, :-2] = torch.ones(3, 3)
print(a)

# 

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 1., 1., 1.]])
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 0., 0.]])


In [0]:
# substract values on sequential index

x = torch.tensor([1, 2, 4, 7, 0])
x_diff = x[1:] - x[:-1]

print(x[1:])
print(x[:-1])
print(x_diff)

tensor([2, 4, 7, 0])
tensor([1, 2, 4, 7])
tensor([ 1,  2,  3, -7])
