<a href="https://colab.research.google.com/github/dejanbatanjac/pytorch-learning-101/blob/master/PyTorch_General.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
# check if you have GPU
import torch
torch.cuda.is_available()

True

In [0]:
# unsqueeze
import torch
x = torch.tensor([1, 2, 3, 4])
print(x,x.shape)
print(torch.unsqueeze(x, 0),torch.unsqueeze(x, 0).shape)
print(torch.unsqueeze(x, 1),torch.unsqueeze(x, 1).shape)

print("...")
print(x.view(-1,1), x.view(-1,1).shape)
print(x.view(1,-1), x.view(1,-1).shape)


tensor([1, 2, 3, 4]) torch.Size([4])
tensor([[1, 2, 3, 4]]) torch.Size([1, 4])
tensor([[1],
        [2],
        [3],
        [4]]) torch.Size([4, 1])
...
tensor([[1],
        [2],
        [3],
        [4]]) torch.Size([4, 1])
tensor([[1, 2, 3, 4]]) torch.Size([1, 4])


In [0]:
from torch.utils.data import DataLoader, Dataset
import numpy as np

x1 = np.array([13,3,28,24,33,2,3,62,47,58])
x2 = np.array([15,21,30,27,17,3,3,54,54,44])
x3 = np.array([32,2,27,19,2,3,32,3,60,47])

#stack multiple tensors using np.stack

md = DataLoader( np.stack([x1,x2,x3], axis=1), batch_size=512)
#??np.stack


In [0]:
import torch
a = [i for i in range(50)]
b = [i for i in range(50)]
c = [i for i in range(50)]

#h
A = torch.Tensor(a)
B = torch.FloatTensor(b)
C = torch.FloatTensor(c)
h=[A,B,C]

print(len(h))
print(h[0].size(), h[0])

3
torch.Size([50]) tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
        14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26., 27.,
        28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39., 40., 41.,
        42., 43., 44., 45., 46., 47., 48., 49.])


In [0]:
import torch 
import torch.utils.data as utils
import numpy as np


# from np.array to tensor
np_x = [np.array([[1,2],[1,3]]),np.array([[5,6],[7,8]])] # a list of numpy arrays
np_y = [np.array([2]), np.array([3])] # another list of numpy arrays (targets)

tx = torch.stack([torch.Tensor(i) for i in np_x]) # transform to torch tensors
ty = torch.stack([torch.Tensor(i) for i in np_y])

print("tensor x:", tx)
print("tensor y:", ty)
print("tensor x shape:", tx.shape)
print("tensor y shape:", ty.shape)

# Dataset is an abstract class. We cannot use it directly.
# We use TensorDataset class.
# The tensor(s) in there should have the same size of the first dimension.

# create datset
ds = utils.TensorDataset(tx, ty) 

# try setting shuffle=False|True
dl = utils.DataLoader(ds, batch_size=1, shuffle=False) 


# DataLoader knows the batch size. Try setting {1|2} instead
dl = utils.DataLoader(ds, batch_size=2, shuffle=True) 


it =iter(dl)
works = True
while works:
    try:
        *r, l = next(it)
        print("--")
        print(r)
        print(l)
        

    except Exception as e:
        print(e)
        works = False


tensor x: tensor([[[1., 2.],
         [1., 3.]],

        [[5., 6.],
         [7., 8.]]])
tensor y: tensor([[2.],
        [3.]])
tensor x shape: torch.Size([2, 2, 2])
tensor y shape: torch.Size([2, 1])
--
[tensor([[[5., 6.],
         [7., 8.]],

        [[1., 2.],
         [1., 3.]]])]
tensor([[3.],
        [2.]])



In [0]:
import torch 
import torch.utils.data as utils

# from list to tensor
l_x = [ [[1,2],[1,3]], [[5,6],[7,8]] ] # a list of numpy arrays
l_y = [ [2],[2]] # another list of numpy arrays (targets)

# transform to torch tensors
tx = torch.stack([torch.Tensor(i) for i in l_x]) 
ty = torch.stack([torch.Tensor(i) for i in l_y])

print(tx)
print(ty)
print(tx.shape, ty.shape)

# Dataset is an abstract class. We cannot use it directly.
# We use TensorDataset class.
# The tensor(s) in there should have the same size of the first dimension.

# create datset
ds = utils.TensorDataset(tx, ty) 
# create dataloader
dl = utils.DataLoader(ds, batch_size=1, shuffle=True) 

# print what we have inside
print("==")
for i in ds: print(i)
print(type(i))
print("==")
for i in dl: print(i)
print(type(i))
    

tensor([[[1., 2.],
         [1., 3.]],

        [[5., 6.],
         [7., 8.]]])
tensor([[2.],
        [2.]])
torch.Size([2, 2, 2]) torch.Size([2, 1])
==
(tensor([[1., 2.],
        [1., 3.]]), tensor([2.]))
(tensor([[5., 6.],
        [7., 8.]]), tensor([2.]))
<class 'tuple'>
==
[tensor([[[5., 6.],
         [7., 8.]]]), tensor([[2.]])]
[tensor([[[1., 2.],
         [1., 3.]]]), tensor([[2.]])]
<class 'list'>


In [0]:
import torch
import torch.nn as nn

tensor = torch.randn((1, 2), requires_grad=True)

print(torch.tanh(tensor))
print(nn.Tanh()(tensor))

#nn.functional.tanh is deprecated
#print(torch.nn.functional.tanh(tensor))

tensor([[0.8146, 0.7732]], grad_fn=<TanhBackward>)
tensor([[0.8146, 0.7732]], grad_fn=<TanhBackward>)


In [0]:
import torch


x = torch.zeros(2,1,2,1,2)
print(x.size())

# all dimensions of size 1 will be removed
y = torch.squeeze(x)
print(y.size())

# we may specify particular dimension to squeeze
# in here 0 will not do anything
y = torch.squeeze(x, 0)
print(y.size())

# we may specify particular dimension to squeeze
# in here 1 will squeeze single dimension
y = torch.squeeze(x, 1)
print(y.size())

torch.Size([2, 1, 2, 1, 2])
torch.Size([2, 2, 2])
torch.Size([2, 1, 2, 1, 2])
torch.Size([2, 2, 1, 2])


In [0]:
# * 
*bb, bbb = [1,2,3,4,5,6,7]
print(bb)
print(bbb)

[1, 2, 3, 4, 5, 6]
7


In [0]:
import torch


x = torch.zeros(2,1)
print(x.size())
print(x)

# all dimensions of size 1 will be removed
y = torch.squeeze(x)
print(y.size())
print(y)

# to be same as x
z = torch.unsqueeze(y, dim=1)
print(z.size())
print(z)



torch.Size([2, 1])
tensor([[0.],
        [0.]])
torch.Size([2])
tensor([0., 0.])
torch.Size([2, 1])
tensor([[0.],
        [0.]])


In [0]:
# from np.array -> tensor
import numpy as np
import torch

#a = np.array([1, 2, 3])
a = np.random.rand(3,2)
t = torch.from_numpy(a)
print(t)



tensor([[0.0307, 0.9624],
        [0.8289, 0.9290],
        [0.4454, 0.1031]], dtype=torch.float64)


In [0]:
print(torch.__version__) #1.0.1.post2
#stacking example
a = torch.randn(2,3,4)
b = torch.randn(2,3)
print(a.size())
print(b.size())
b = torch.unsqueeze(b, dim=2)  # 2, 3, 1
print(b.size())



1.0.1.post2
torch.Size([2, 3, 4])
torch.Size([2, 3])
torch.Size([2, 3, 1])


In [0]:
import torch
print(torch.__version__) # 1.0.1.post2
#stacking example
a = torch.randn(2,3,4)
b = torch.randn(2,3)
print(a.size()) # 2, 3, 4
print(b.size()) # 2, 3
b = torch.unsqueeze(b, dim=2)  
print(b.size()) # 2, 3, 1

r = torch.cat((a,b), dim=2)
# r = torch.stack([a, b], dim=2 )
print(r.shape)
print(r)

1.0.1.post2
torch.Size([2, 3, 4])
torch.Size([2, 3])
torch.Size([2, 3, 1])
torch.Size([2, 3, 5])
tensor([[[ 0.0139,  0.6015, -1.6427,  0.9218, -0.4895],
         [-1.4400,  1.8444,  0.5984,  1.7035, -0.7307],
         [-0.4477, -0.0331, -1.7182, -1.9063,  0.6845]],

        [[ 0.2214,  0.3788, -1.1672,  0.4438, -0.6435],
         [ 0.9548,  1.5609,  1.2947,  0.5860,  0.7537],
         [ 1.5375, -0.5452, -0.9654,  1.0114,  0.2838]]])


In [0]:
#transpose 2D Tensor (dimensions 0 <=> 1)
x = torch.randn(2, 3)
print(x)
y = torch.t(x)
print(y)



tensor([[ 0.7538,  0.3490,  0.4196],
        [ 0.8518,  0.2454, -0.4683]])
tensor([[ 0.7538,  0.8518],
        [ 0.3490,  0.2454],
        [ 0.4196, -0.4683]])


In [0]:
#get tensor based on indices

arr=torch.tensor([[1,2],[4,5],[7,8]])
indices_arr=torch.tensor([0,1,0])

ret=arr[[0,1,2],indices_arr]
print(ret, type(ret))

tensor([1, 5, 7]) <class 'torch.Tensor'>


In [0]:
import torch

a = torch.Tensor([1,2,3,4,5])
print(a.shape)
print(a)

a.unsqueeze_(dim=1)
print(a.shape)
print(a)

# a.unsqueeze_(dim=0)
# print(a.shape)
# print(a)



torch.Size([5])
tensor([1., 2., 3., 4., 5.])
torch.Size([5, 1])
tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.]])


In [10]:
# smart indexing example
import torch

x = torch.arange(0, 10, dtype=torch.float)
print(x)

# getting indexes idx where x>=5
idx = x>=5
print(idx, type(idx))

# log on values where x was >=5
x[idx] = torch.log(x[idx])
print(x)

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])
tensor([0, 0, 0, 0, 0, 1, 1, 1, 1, 1], dtype=torch.uint8) <class 'torch.Tensor'>
tensor([0.0000, 1.0000, 2.0000, 3.0000, 4.0000, 1.6094, 1.7918, 1.9459, 2.0794,
        2.1972])
